### ISSUE TITLE
Class 'Symfony\Component\HttpKernel\Kernel' not found 

### ISSUE THREAD

**Issue by ricohumme** [sensiolabs/SensioDistributionBundle#302] opened 2016-12-27 21:09 UTC
Hi,

After this class got removed it started giving me issues with the bootstrap.php.cache not loading this class.
When setting this class back in the array of classes in method `doBuildBootstrap`, the error went away and I could resume my work.
This happened when executing console commands, like cache:clear or whatever.
For the record: This project still uses app/console but this should not be this issue (i think)

I found this commit to be the problem:
https://github.com/sensiolabs/SensioDistributionBundle/commit/7046e6e939bf1b2c1cccce954bd2b4463cc9dceb#diff-15440fa683820b6e7d858e22d328f613

Why was this removed in the first place?

**Comment by tjveldhuizen** [comment] 2017-01-06 14:28
The commit is mentioned in:
- https://github.com/symfony/symfony/issues/20753
- https://github.com/sensiolabs/SensioDistributionBundle/pull/297

and seems to be a fix for a Symfony 3.2-environment. However, I'm using Symfony 2.8, where it results in the problem as @ricohumme mentioned above.

**Comment by ricohumme** [comment] 2017-01-06 14:59
I'm using SF 3.2.1 BTW

**Comment by ChristineATA** [comment] 2017-01-06 15:35
Hi,

I have the same issue, and i'm using Symfony 2.8 as @tjveldhuizen mentionned above.
I was using SensioDistributionBundle v3, and tried to upgrade to 5.0.17.

**Comment by billsworld** [comment] 2017-01-19 04:47
I am able to reproduce this issue with Symfony 3. As soon as I revert sensio/distribution-bundle (v5.0.15 => v5.0.14) everything starts working again.

Let me know if I can provide further configuration form my end.

**Comment by HeahDude** [comment] 2017-01-19 07:26
Hello everyone, thank you for confirming this issue.

What would really help is some basic steps to reproduce it from scratch, can anyone please provide that?

/cc @nicolas-grekas

**Comment by ChristineATA** [comment] 2017-01-19 09:37
Hello,

Here is the require part of my composer.json 

```
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "~2.8",
        "symfony/assetic-bundle": "^2.6",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~3.0.2",
        
        "doctrine/orm": "~2.4",
        "doctrine/doctrine-bundle": "~1.4",
        
        "twig/twig": "~1.23",
        "twig/extensions": "1.0.1",

	"sensio/framework-extra-bundle": "3.0.2",
	"sensio/generator-bundle": "~3.0",
        "sensio/distribution-bundle": "~5.0",

        "incenteev/composer-parameter-handler": "~2.0",
        "leafo/lessphp" : "0.4.0", 
        "jquery/jquery": "1.11.1",
        "imsky/holder": "master-dev",
        "robertotru/to-inline-style-email-bundle": "dev-master",
        "jms/security-extra-bundle": "dev-master",
        "apy/datagrid-bundle": "dev-master",
        "knplabs/knp-snappy-bundle": "dev-master",
        
        "friendsofsymfony/user-bundle": "v2.0.0-alpha3",
        "friendsofsymfony/jsrouting-bundle": "dev-master",

        "bitgrave/barcode-bundle": "dev-master"
    },
```
When I do the update command, I get the error in the "clearCache" step.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating sensiolabs/security-checker (v3.0.2 => v4.0.0) Loading from cache
  - Removing sensio/distribution-bundle (v4.0.38)
  - Installing sensio/distribution-bundle (v5.0.18) Downloading: 100%
Writing lock file
Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Class 'Symfony\Component\HttpKernel\Kernel' not found in _XXXX_\app\AppKernel.php on line 7
PHP Fatal error:  Class 'Symfony\Component\HttpKernel\Kernel' not found in _XXXX_\app\AppKernel.php on line 7
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl
ing the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:
  Fatal error: Class 'Symfony\Component\HttpKernel\Kernel' not found in _XXXX_\app\AppKernel.php on line 7
  PHP Fatal error:  Class 'Symfony\Component\HttpKernel\Kernel' not found in
  _XXXX_\app\AppKernel.php on line 7
  .

```

For me it's not really problematic because when I revert to distribution-bundle 4.0.38 it's working fine.

Maybe it's an incompatibility problem, please tell me if I'm doing something wrong.

**Comment by HeahDude** [comment] 2017-01-19 22:21
I've opened https://github.com/sensiolabs/SensioDistributionBundle/pull/308, can someone please confirm if this is actually fixing your issue? Thanks!

**Comment by ChristineATA** [comment] 2017-01-20 09:41
Hi,
Thanks for the fix, but it's still not working.
I went into the code and i think there is two issues :

First, in the exectueBuildBootstrap function :
```
$autoloadDir = escapeshellarg($autoloadDir)
static::checkNeedsInlineKernelClass($event, $autoloadDir);
```
The $autoloadDir contain "app" (with the quotes), so the "in_array" of the checkNeedsInlineKernelClass function won't return "true".

Second, i got the self::$needsInlineKernelClass to true (by switching the two lines above to test), but it goes back to false in the doBuildBootstrap function, i don't understand why (maybe because of the "Process" class ?)

I don't know if i'm clear, i'm no expert :)

**Comment by HeahDude** [comment] 2017-01-20 16:29
Thank you @ChristineATA for your feedback.

Looks right you're right, the static property is reset, because the process run in its own shell :/

I don't know how to fix this for now, I'm not an expert of the `Process` component either :)

**Comment by HeahDude** [comment] 2017-01-20 17:59
@ChristineATA I've updated #308 could you have a look? Thanks!

**Comment by ChristineATA** [comment] 2017-01-24 08:16
Hi @HeahDude, sorry for the delay.

I get a new error this time:

```
Fatal error: Class 'Symfony\Component\Console\Input\ArgvInput' not found in C:\G
IT\PHP\ATASITES2\espaces-partenaires\app\console on line 17
PHP Fatal error:  Class 'Symfony\Component\Console\Input\ArgvInput' not found in
 XXX\app\console on line 17
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl
ing the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:
  Fatal error: Class 'Symfony\Component\Console\Input\ArgvInput' not found in
   XXX\app\console on line 17
  PHP Fatal error:  Class 'Symfony\Component\Console\Input\ArgvInput' not fou
  nd in XXX\app\console on line 17
  .

```

Sorry that I don't have time to debug like last time but maybe it's telling you something? 
Thanks!

**Comment by HeahDude** [comment] 2017-01-28 17:46
Hey @ChristineATA, thank you again for testing it. However this error does not seem related, apparently you're using the old directory structure with `console` in the `app/` folder instead of `bin/` and maybe the autoload is wrongly configured there. That's what the message could mean.

Can you please tell use what's your version of symfony and this bundle?

Could anyone who encounters this issue test the https://github.com/sensiolabs/SensioDistributionBundle/pull/308 to confirm the fix works?

Thanks!

**Comment by ricohumme** [comment] 2017-01-28 17:51
Hi,

I encountered this once with the new directory structure, with bin/console. 

Verstuurd vanaf mijn iPhone

**Comment by smatyas** [comment] 2017-02-11 18:59
Hi, I faced the same problem while I was **upgrading a symfony 2.0 project to 2.8.**
I think it's unrelated to this bundle, but I got here by searching the output in google, so hopefully it will help someone :)

I found that this was caused by autoloading changes between those symfony versions.
You should compare your files to a newly generated empty 2.8 symfony project.
The following changes solved my issue:

1. put `AppKernel` and `AppCache` in the autoload section of composer.json
```
   "autoload": {
     "psr-4": {
       "": "src/"
-    }
+    },
+    "classmap": [
+      "app/AppKernel.php",
+      "app/AppCache.php"
+    ]
   },
```

2. in `app.php` and `app_dev.php` require the `app/autoload.php` instead of `app/bootstrap.php.cache` and skip the `app/AppKernel.php` require (that will be autoloaded).
```
-$loader = require_once __DIR__.'/../app/bootstrap.php.cache';
-require_once __DIR__.'/../app/AppKernel.php';
+/** @var \Composer\Autoload\ClassLoader $loader */
+$loader = require __DIR__.'/../app/autoload.php';
```

**The root cause of the error was the `require_once __DIR__.'/../app/AppKernel.php';` line, because at that time the autoloader was not yet loaded.**

**Comment by davidm013** [comment] 2017-02-21 13:30
The problem is in the app/console file, replace the file from a fresh install of symfony 2.8 and remove this lines in the routing_dev.xml

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

For me it's working.

**Comment by Saloua2017** [comment] 2017-02-22 11:31
@smatyas: Thank you for sharing, that solved my problem 👍

**Comment by vesper8** [comment] 2017-03-25 09:53
I tried applying @smatyas changes in order to make this error go away when running Mautic on php 7.1 but it didn't work. I know that's a different project outside the scope of this issue but it seems to be the same problem so if any of you feel like having a look that would be appreciated!

**Comment by 0x46616c6b** [comment] 2017-04-13 23:32
For me (upgraded Symfony 2.8 to 3.2) the update of bin/console (https://github.com/symfony/symfony-standard/blob/3.2/bin/console#L16) solves the problem.

**Comment by sampart** [comment] 2017-07-21 11:50
@smatyas's [comment](#issuecomment-279167771) solved the problem for me, thanks!  I was upgrading from Symfony 2.3 to 2.4 and like him found this thread via Google (my situation was unrelated to SensioDistributionBundle too).

I also had the "kernel not found" error when running `app/console`, so I also had to change `console.php`:

```
+/**
+ * @var Composer\Autoload\ClassLoader $loader
+ */
+$loader = require __DIR__.'/autoload.php';
+
 require_once __DIR__.'/bootstrap.php.cache';
 require_once __DIR__.'/AppKernel.php';
 
 use Symfony\Bundle\FrameworkBundle\Console\Application;
 use Symfony\Component\Console\Input\ArgvInput;
 
-/**
- * @var Composer\Autoload\ClassLoader $loader
- */
-$loader = require __DIR__.'/autoload.php';
```

(BTW, it looks like the relevant [Symfony Standard edition version](https://github.com/symfony/symfony-standard/blob/2.4/app/console) of `console.php` doesn't have the `$loader` line that I moved, so the change if you're using that would be adding it, not moving it.)

**Comment by florianwagner81** [comment] 2019-02-07 10:52
Afterwards I still needed a "_**composer dump-autoload**_" on the target system...but in general your solution worked for me!

**Comment by HeahDude** [comment] 2019-11-29 19:19
Closing here, since comments seem to have fixed all issues. Thanks!

**Closed by HeahDude** 2019-11-29 19:19 UTC
Labels: Bug, has PR
